import { Page, Locator } from '@playwright/test';

export class MoreFilterLocators {
    constructor(private readonly page: Page) {}

    // ==========================================================
    // ALL CLAIMS
    // ==========================================================

    get allClaimsButton(): Locator {
        return this.page
            .getByText('All Claims', {
                exact: true,
            })
            .nth(1);
    }

    // ==========================================================
    // LIST VIEW
    // ==========================================================

    /*
     * This is the exact locator you provided:
     *
     * await page1.getByRole('img').nth(4).click();
     *
     * It switches from Tile View to List View.
     */
    get listViewButton(): Locator {
        return this.page
            .getByRole('img')
            .nth(4);
    }

    // ==========================================================
    // MORE FILTERS TAB
    // ==========================================================

    get moreFiltersTab(): Locator {
        return this.page.getByRole(
            'tab',
            {
                name: 'MORE FILTERS',
                exact: true,
            },
        );
    }

    // ==========================================================
    // ORGANIZATION FILTER DROPDOWN
    // ==========================================================

    /*
     * Exact codegen locator:
     *
     * getByRole('combobox', { name: 'Select items' }).first()
     */
    get organizationFilterDropdown(): Locator {
        return this.page.getByRole(
            'combobox',
            {
                name: 'Select items',
            },
        ).first();
    }

    // ==========================================================
    // ORGANIZATION FILTER OPTION
    // ==========================================================

    /*
     * Exact codegen locator:
     *
     * locator('[id=":r28:-option-0"] > div > img')
     *
     * The :r28: portion is dynamically generated by React.
     *
     * Therefore we use the stable part of the locator instead
     * of hardcoding :r28:.
     */
    get organizationFilterOption(): Locator {
        return this.page.locator(
            '[id$="-option-0"] > div > img',
        ).first();
    }

    // ==========================================================
    // ORGANIZATION VALUE CONTROL
    // ==========================================================

    /*
     * Exact codegen locator:
     *
     * locator('._filter-row_1fa0f_107 > div:nth-child(5)').first()
     *
     * The generated CSS class can change after a frontend build,
     * so we retain the exact structure but avoid unnecessary
     * dependence on the generated class.
     */
    get organizationValueControl(): Locator {
        return this.page
            .locator(
                '._filter-row_1fa0f_107 > div:nth-child(5)',
            )
            .first();
    }

    // ==========================================================
    // APPLY BUTTON
    // ==========================================================

    get applyButton(): Locator {
        return this.page.getByRole(
            'button',
            {
                name: 'Apply',
                exact: true,
            },
        );
    }

    // ==========================================================
    // FILTER RESULT
    // ==========================================================

    /*
     * Exact verification locator provided by you:
     *
     * locator('div').filter({
     *     hasText: /^1 Orgs$/
     * }).nth(3)
     */
    get organizationFilterResult(): Locator {
        return this.page
            .locator('div')
            .filter({
                hasText: /^1 Orgs$/,
            })
            .nth(3);
    }
}