import { google } from 'googleapis';

import fs from 'node:fs';

import path from 'node:path';

// ==========================================================
// FILE PATHS
// ==========================================================

const CREDENTIALS_PATH = path.resolve(
  __dirname,
  '../credentials.json'
);

const TOKEN_PATH = path.resolve(
  __dirname,
  '../token.json'
);

// ==========================================================
// EMAIL CONFIGURATION
// ==========================================================

const RECIPIENT1 =
  'vibha.laxmi@thecadre.in';

// const RECIPIENT2 =
//   'sunil.rangaiah@thecadre.in';

const SENDER =
  'vibha.laxmi+odradmin@thecadre.in';

// ==========================================================
// TYPES
// ==========================================================

export interface SuiteReport {

  totalScenarios: number;

  passedScenarios: number;

  failedScenarios: number;

  skippedScenarios: number;
}

// ==========================================================
// GET GMAIL AUTHENTICATION
// ==========================================================

async function getSavedAuth() {

  // ========================================================
  // CHECK CREDENTIALS
  // ========================================================

  if (
    !fs.existsSync(
      CREDENTIALS_PATH
    )
  ) {

    throw new Error(
      `credentials.json not found:\n${CREDENTIALS_PATH}`
    );
  }

  // ========================================================
  // CHECK TOKEN
  // ========================================================

  if (
    !fs.existsSync(
      TOKEN_PATH
    )
  ) {

    throw new Error(
      `token.json not found:\n${TOKEN_PATH}`
    );
  }

  // ========================================================
  // READ CREDENTIALS
  // ========================================================

  const credentials =
    JSON.parse(
      fs.readFileSync(
        CREDENTIALS_PATH,
        'utf8'
      )
    );

  const config =
    credentials.installed ??
    credentials.web;

  if (!config) {

    throw new Error(
      'Invalid credentials.json. ' +
      'Expected "installed" or "web".'
    );
  }

  // ========================================================
  // CREATE OAUTH CLIENT
  // ========================================================

  const auth =
    new google.auth.OAuth2(
      config.client_id,
      config.client_secret,
      config.redirect_uris[0]
    );

  // ========================================================
  // READ TOKEN
  // ========================================================

  const token =
    JSON.parse(
      fs.readFileSync(
        TOKEN_PATH,
        'utf8'
      )
    );

  // ========================================================
  // SET TOKEN
  // ========================================================

  auth.setCredentials(
    token
  );

  return auth;
}

// ==========================================================
// CREATE EMAIL BODY
// ==========================================================

function createEmail(
  report: SuiteReport
): string {

  const overallStatus =
    report.failedScenarios === 0 &&
    report.skippedScenarios === 0
      ? 'PASSED'
      : 'FAILED';

  let body = '';

  body +=
    'BULK ACTIONS SUITE REPORT\n';

  body +=
    '\n';

  body +=
    '======================================================\n';

  body +=
    'SUITE SUMMARY\n';

  body +=
    '======================================================\n';

  body +=
    `Overall Status : ${overallStatus}\n`;

  body +=
    `Total Scenarios : ${report.totalScenarios}\n`;

  body +=
    `Passed          : ${report.passedScenarios}\n`;

  body +=
    `Failed          : ${report.failedScenarios}\n`;

  body +=
    `Skipped         : ${report.skippedScenarios}\n`;

  body +=
    '======================================================\n';

  body +=
    '\n';

  body +=
    'Scenarios covered:\n';

  body +=
    '1. Verify Actions button is visible after selecting a claim\n';

  body +=
    '2. Assign Case Officer and verify inside the claim\n';

  body +=
    '\n';

  body +=
    'This report was automatically generated by Playwright.\n';

  return body;
}

// ==========================================================
// SEND REPORT
// ==========================================================

export async function sendReport(
  report: SuiteReport
): Promise<void> {

  console.log('');

  console.log(
    '======================================================'
  );

  console.log(
    '              SENDING BULK ACTIONS REPORT'
  );

  console.log(
    '======================================================'
  );

  // ========================================================
  // GET GMAIL AUTHENTICATION
  // ========================================================

  const auth =
    await getSavedAuth();

  // ========================================================
  // CREATE GMAIL CLIENT
  // ========================================================

  const gmail =
    google.gmail({
      version: 'v1',
      auth,
    });

  // ========================================================
  // DETERMINE OVERALL STATUS
  // ========================================================

  const overallStatus =
    report.failedScenarios === 0 &&
    report.skippedScenarios === 0
      ? 'PASSED'
      : 'FAILED';

  // ========================================================
  // EMAIL SUBJECT
  // ========================================================

  const subject =
    `[${overallStatus}] Bulk Actions Suite Report`;

  // ========================================================
  // EMAIL BODY
  // ========================================================

  const body =
    createEmail(
      report
    );

  // ========================================================
  // RAW EMAIL
  // ========================================================

  const emailLines = [

    `From: ${SENDER}`,

    `To: ${RECIPIENT1}`,

    // If you want another recipient later:
    // `Cc: ${RECIPIENT2}`,

    `Subject: ${subject}`,

    'Content-Type: text/plain; charset="UTF-8"',

    '',

    body,
  ];

  const rawEmail =
    emailLines.join(
      '\r\n'
    );

  // ========================================================
  // BASE64URL ENCODE
  // ========================================================

  const encodedEmail =
    Buffer.from(
      rawEmail,
      'utf8'
    )
      .toString('base64')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');

  // ========================================================
  // SEND EMAIL
  // ========================================================

  await gmail.users.messages.send({

    userId: 'me',

    requestBody: {

      raw: encodedEmail,
    },
  });

  // ========================================================
  // SUCCESS
  // ========================================================

  console.log('');

  console.log(
    'Email sent successfully.'
  );

  console.log(
    `Recipient: ${RECIPIENT1}`
  );

  console.log(
    `Overall Status: ${overallStatus}`
  );

  console.log(
    `Total Scenarios: ${report.totalScenarios}`
  );

  console.log(
    `Passed Scenarios: ${report.passedScenarios}`
  );

  console.log(
    `Failed Scenarios: ${report.failedScenarios}`
  );

  console.log('');

  console.log(
    '======================================================'
  );
}