import {
    expect,
    Page,
    Locator,
} from '@playwright/test';


// ==========================================================
// MESSAGE TAGS PAGES
// ==========================================================

export class MessageTagsPages {

    constructor(
        private readonly page: Page
    ) {}


    // ==========================================================
    // FIND FIRST ORDER MESSAGE
    // ==========================================================

    private targetMessage(): Locator {

        return this.page.getByText(
            'First Order',
            {
                exact: true,
            }
        ).first();
    }


    // ==========================================================
    // FIND MESSAGE CONTAINER
    //
    // The actual DOM generated by Codegen is similar to:
    //
    // #message-947160
    //     └── .translation-icons
    //             ├── img
    //             ├── img
    //             └── img  <-- ACTION / 3 DOT ICON
    //
    // We therefore find the message container first instead
    // of searching random ancestor images.
    // ==========================================================

    private async findMessageContainer(): Promise<Locator> {

        const targetMessage =
            this.targetMessage();


        await expect(
            targetMessage
        ).toBeVisible({
            timeout: 30000,
        });


        await targetMessage.scrollIntoViewIfNeeded();


        console.log(
            'Finding parent message container...'
        );


        // ======================================================
        // FIND AN ANCESTOR HAVING id="message-xxxxx"
        // ======================================================

        const messageContainer =
            targetMessage.locator(
                'xpath=ancestor::*[starts-with(@id, "message-")]'
            ).first();


        await expect(
            messageContainer
        ).toHaveCount(
            1,
            {
                timeout: 15000,
            }
        );


        console.log(
            'Message container found successfully.'
        );


        return messageContainer;
    }


    // ==========================================================
    // FIND CORRECT MESSAGE ACTION ICON
    //
    // IMPORTANT:
    //
    // DO NOT search all <img> elements in parent levels.
    //
    // Codegen showed:
    //
    // #message-xxxxx >
    // .translation-icons >
    // img:nth-child(3)
    //
    // Therefore we specifically target the THIRD IMAGE inside
    // the translation-icons container.
    // ==========================================================

    private async findMessageActionIcon(): Promise<Locator> {

        const messageContainer =
            await this.findMessageContainer();


        // ======================================================
        // FIND TRANSLATION ICON CONTAINER
        //
        // We intentionally use [class*="translation-icons"]
        // instead of the complete generated CSS class because
        // the suffix such as "_1quil_291" can change after a
        // frontend build.
        // ======================================================

        const translationIcons =
            messageContainer.locator(
                '[class*="translation-icons"]'
            ).first();


        await expect(
            translationIcons
        ).toHaveCount(
            1,
            {
                timeout: 15000,
            }
        );


        await expect(
            translationIcons
        ).toBeVisible({
            timeout: 15000,
        });


        console.log(
            'Translation/action icon container found.'
        );


        // ======================================================
        // FIND THIRD IMAGE
        //
        // Codegen:
        //
        // img:nth-child(3)
        //
        // Playwright nth() is zero based, so:
        //
        // nth(0) = first
        // nth(1) = second
        // nth(2) = third
        // ======================================================

        const actionIcon =
            translationIcons.locator(
                'img'
            ).nth(2);


        await expect(
            actionIcon
        ).toBeVisible({
            timeout: 15000,
        });


        console.log(
            'Correct message action icon found.'
        );


        return actionIcon;
    }


    // ==========================================================
    // STEP 1 - OPEN TARGET MESSAGE
    // ==========================================================

    async openTargetMessage(): Promise<void> {

        console.log('');
        console.log(
            '======================================================'
        );

        console.log(
            'STEP 1 - FIND FIRST ORDER MESSAGE'
        );

        console.log(
            '======================================================'
        );


        const targetMessage =
            this.targetMessage();


        await expect(
            targetMessage
        ).toBeVisible({
            timeout: 30000,
        });


        console.log(
            'First Order message found successfully.'
        );


        await targetMessage.scrollIntoViewIfNeeded();


        /*
         * Click the First Order message text.
         *
         * This is only used to bring/open the target message.
         */

        await targetMessage.click();


        await this.page.waitForTimeout(
            1000
        );


        console.log(
            'First Order message opened successfully.'
        );
    }


    // ==========================================================
    // STEP 2 - OPEN MESSAGE TAG MENU
    // ==========================================================

    async openMessageTagMenu(): Promise<void> {

        console.log('');
        console.log(
            '======================================================'
        );

        console.log(
            'STEP 2 - OPEN MESSAGE TAG MENU'
        );

        console.log(
            '======================================================'
        );


        // ======================================================
        // VERIFY TARGET MESSAGE
        // ======================================================

        const targetMessage =
            this.targetMessage();


        await expect(
            targetMessage
        ).toBeVisible({
            timeout: 30000,
        });


        await targetMessage.scrollIntoViewIfNeeded();


        // ======================================================
        // FIND CORRECT ACTION ICON
        // ======================================================

        const actionIcon =
            await this.findMessageActionIcon();


        await expect(
            actionIcon
        ).toBeVisible({
            timeout: 15000,
        });


        await actionIcon.scrollIntoViewIfNeeded();


        console.log(
            'Correct 3-dot/message action icon found.'
        );


        // ======================================================
        // CLICK CORRECT ACTION ICON
        // ======================================================

        await actionIcon.click();


        await this.page.waitForTimeout(
            500
        );


        console.log(
            'Message tag menu opened successfully.'
        );


        // ======================================================
        // VERIFY MENU
        // ======================================================

        const secondOrderOption =
            this.page.getByText(
                'Mark Message as Second Order',
                {
                    exact: true,
                }
            );


        const thirdOrderOption =
            this.page.getByText(
                'Mark Message as Third Order',
                {
                    exact: true,
                }
            );


        const fourthOrderOption =
            this.page.getByText(
                'Mark Message as Fourth Order',
                {
                    exact: true,
                }
            );


        const secondVisible =
            await secondOrderOption
                .isVisible()
                .catch(
                    () => false
                );


        const thirdVisible =
            await thirdOrderOption
                .isVisible()
                .catch(
                    () => false
                );


        const fourthVisible =
            await fourthOrderOption
                .isVisible()
                .catch(
                    () => false
                );


        if (
            !secondVisible &&
            !thirdVisible &&
            !fourthVisible
        ) {

            throw new Error(
                [
                    'Message tag menu did not open.',
                    'Expected message tag options were not found.',
                    `Current URL: ${this.page.url()}`,
                ].join('\n')
            );
        }


        console.log(
            'Message tag menu verified successfully.'
        );
    }


    // ==========================================================
    // APPLY MESSAGE TAG
    // ==========================================================

    async applyTag(
        tag: string
    ): Promise<void> {

        console.log('');
        console.log(
            `Applying message tag: ${tag}`
        );


        // ======================================================
        // MAP TAG TO UI TEXT
        // ======================================================

        let menuOptionText: string;


        switch (
            tag
        ) {

            case 'First Message':

                menuOptionText =
                    'Mark Message as First Message';

                break;


            case 'Second Order':

                menuOptionText =
                    'Mark Message as Second Order';

                break;


            case 'Third Order':

                menuOptionText =
                    'Mark Message as Third Order';

                break;


            case 'Fourth Order':

                menuOptionText =
                    'Mark Message as Fourth Order';

                break;


            default:

                throw new Error(
                    [
                        `Unsupported message tag: ${tag}`,
                        'Supported tags:',
                        'First Message',
                        'Second Order',
                        'Third Order',
                        'Fourth Order',
                    ].join('\n')
                );
        }


        // ======================================================
        // FIND OPTION
        // ======================================================

        const option =
            this.page.getByText(
                menuOptionText,
                {
                    exact: true,
                }
            ).last();


        await expect(
            option
        ).toBeVisible({
            timeout: 15000,
        });


        await option.scrollIntoViewIfNeeded();


        // ======================================================
        // CLICK OPTION
        // ======================================================

        await option.click();


        await this.page.waitForTimeout(
            700
        );


        console.log(
            `Message tag applied successfully: ${tag}`
        );
    }


    // ==========================================================
    // APPLY FIRST MESSAGE
    // ==========================================================

    async applyFirstMessage(): Promise<void> {

        await this.applyTag(
            'First Message'
        );
    }


    // ==========================================================
    // APPLY SECOND ORDER
    // ==========================================================

    async applySecondOrder(): Promise<void> {

        await this.applyTag(
            'Second Order'
        );
    }


    // ==========================================================
    // APPLY THIRD ORDER
    // ==========================================================

    async applyThirdOrder(): Promise<void> {

        await this.applyTag(
            'Third Order'
        );
    }


    // ==========================================================
    // APPLY FOURTH ORDER
    // ==========================================================

    async applyFourthOrder(): Promise<void> {

        await this.applyTag(
            'Fourth Order'
        );
    }


    // ==========================================================
    // VERIFY FIRST ORDER MESSAGE
    // ==========================================================

    async verifyFirstOrderMessage(): Promise<void> {

        const firstOrder =
            this.page.getByText(
                'First Order',
                {
                    exact: true,
                }
            ).first();


        await expect(
            firstOrder
        ).toBeVisible({
            timeout: 15000,
        });


        console.log(
            'First Order message verified successfully.'
        );
    }
}