name: Cadre ODR Sanity E2E

on:
  schedule:
    - cron: '30 16 * * *'
      timezone: 'Asia/Kolkata'

  workflow_dispatch:

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Sanity E2E
        run: npx playwright test tests/Suites/SanitySuite.spec.ts --project=chromium